name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build
      run: mvn -B package --file pom.xml
    - name: Test spotless #Deja build-ul se ocupa de spotless, dar sa fim siguri :)
      run: mvn spotless:check
    - name: Aplica teste
      run: mvn test
